// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Ny4FsFciXKC-jh7_SdexQi36_bewNEM',
    appId: '1:831761597377:web:86fdc3b4268b4e3944e540',
    messagingSenderId: '831761597377',
    projectId: 'starktracklog',
    authDomain: 'starktracklog.firebaseapp.com',
    storageBucket: 'starktracklog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5zsqzKMp7v4MzlwzGTNQRD2T61ZS4FO0',
    appId: '1:831761597377:android:34b9161fd1a8f25b44e540',
    messagingSenderId: '831761597377',
    projectId: 'starktracklog',
    storageBucket: 'starktracklog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJL1PGPNTiS7hVkpy0h5nogcIO-OxMKrw',
    appId: '1:831761597377:ios:964369a7fbb4648b44e540',
    messagingSenderId: '831761597377',
    projectId: 'starktracklog',
    storageBucket: 'starktracklog.firebasestorage.app',
    iosBundleId: 'com.example.starktrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJL1PGPNTiS7hVkpy0h5nogcIO-OxMKrw',
    appId: '1:831761597377:ios:964369a7fbb4648b44e540',
    messagingSenderId: '831761597377',
    projectId: 'starktracklog',
    storageBucket: 'starktracklog.firebasestorage.app',
    iosBundleId: 'com.example.starktrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Ny4FsFciXKC-jh7_SdexQi36_bewNEM',
    appId: '1:831761597377:web:45097ee1c8c62e2b44e540',
    messagingSenderId: '831761597377',
    projectId: 'starktracklog',
    authDomain: 'starktracklog.firebaseapp.com',
    storageBucket: 'starktracklog.firebasestorage.app',
  );
}
